### ISSUE TITLE
How to add multiple authors.

### ISSUE THREAD

**Issue by asreerama** [stsewd/ieee-pandoc-template#11]
Adding another author in the yaml file does not format the 2 authors as expected. Please could you tell me how one can do that .

**Comment by stsewd** [comment]
Can you please put the content you are trying? This should work

```yaml
author:
  - name: Name One
    affiliation: One
    location: One
    email: one@email.com
  - name: Name Two
    affiliation: Two
    location: Two
    email: two@email.com
```

**Comment by csreid** [comment]
I bet I'm having a similar issue.

If I clone a fresh version of this repo, change `metadata.yaml` to:

```yaml
---
title: 'Paper Title'
author:
  - name: Santos Gallegos
    affiliation: Universidad de Cuenca
    location: Cuenca, Ecuador
    email: santos_g@email.com
  - name: Another Author
    affiliation: University of Phoenix
    location: Online
    email: another@author.com
keywords:
  - one
  - two
  - three
numbersections: yes
lang: en
babel-lang: english
abstract: |
  This is the abstract.

  It consists of two paragraphs.
...

```

(note the new second author) and run `make`, I get this:

![](https://user-images.githubusercontent.com/862383/88414017-31b06680-cdaa-11ea-81a7-d9e8e42c4ec6.png)'

The University affiliation is on the same line as the author's name, and the next author's name starts on the same line as the previous author's email
